package com.tactfactory.calculator;

/**
 * Command to Addition a value.
 */
public class Addition extends CommandBase {

    /**
     * Constructor of command with initial value.
     * @param a Initial value.
     */
    public Addition(final int a) {
        super(a);
    }

    /**
     * Apply value in command.
     * @param b value to apply.
     */
    @Override
    public void make(final int b) {
        this.value = this.value + b;
    }

    /**
     * Get Value generated by command.
     * @return Current value.
     */
    @Override
    public int getValue() {
        return this.value;
    }
}
